# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44d1d538e604a89cc7c972e648fee1fab2eef9f3ce945ae33326e6fa098193ae6da57813dbed3ce068dc920abaef9c5c47cac024ae2192dd3735eb2f224ebda8

test:
  secret_key_base: d80bb1cd07ad9a16e0e5a887e2643abee651e6238876345208aba5d07c244ffa13daab86b67fed73cc2fa753094c6e32ff5ab37be0f76a0b8b32d296943f15dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
